{
  "openapi": "3.0.4",
  "info": {
    "title": "MSH API v2",
    "description": "Meldingstjener Rest API. Default API version.",
    "version": "v2"
  },
  "paths": {
    "/Messages/{id}/apprec": {
      "get": {
        "tags": [
          "MessagesController"
        ],
        "summary": "Get ApprecInfo for the message's ApplicationReceipt. if any.",
        "operationId": "GetApprecInfo",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id of message, as received from GET Messages endpoint (must be a valid Guid)",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          },
          {
            "name": "api-version",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "2"
          },
          {
            "name": "nhn-source-system",
            "in": "header",
            "description": "Name and version for the client system",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "MyApplication, v1.337"
          }
        ],
        "responses": {
          "400": {
            "description": "Bad request - The request was cancelled",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "Request was cancelled",
                  "errorCode": 0,
                  "validationErrors": null,
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "8805ba1c-4ace-4476-94c5-c87f53b697ca"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden - Authenticated client is not authorized to access message with given id",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "Not authorized for HerId(s): 1234",
                  "errorCode": 0,
                  "validationErrors": null,
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "79e34c19-f442-4540-95ca-a69ecc87de48"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error - Unexpected server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "An unknown error occurred",
                  "errorCode": 0,
                  "validationErrors": null,
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "86d7105f-a71c-47fe-a856-b40bb975a000"
                }
              }
            }
          },
          "200": {
            "description": "OK - A list with statuses for message with given id",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/ApprecInfo"
                  }
                },
                "example": [
                  {
                    "receiverHerId": 42,
                    "appRecStatus": "Rejected",
                    "appRecErrorList": [
                      {
                        "errorCode": "E10",
                        "details": "Ugyldig meldingsidentifikator",
                        "description": null,
                        "oid": null
                      }
                    ]
                  }
                ]
              }
            }
          },
          "404": {
            "description": "Not found - Message with given id could not be found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "Could not find database document",
                  "errorCode": 0,
                  "validationErrors": null,
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "d4d0118b-a00c-4016-b715-80368b1a4af8"
                }
              }
            }
          }
        }
      }
    },
    "/Messages": {
      "get": {
        "tags": [
          "MessagesController"
        ],
        "summary": "Get a list of unread messages",
        "operationId": "GetMessages",
        "parameters": [
          {
            "name": "ReceiverHerIds",
            "in": "query",
            "description": "Which messages sent to given HER-ids (one or more) to fetch.",
            "required": true,
            "schema": {
              "uniqueItems": true,
              "type": "array",
              "items": {
                "type": "integer",
                "format": "int32"
              },
              "example": [
                42,
                1337
              ]
            },
            "example": [
              42,
              1337
            ]
          },
          {
            "name": "SenderHerId",
            "in": "query",
            "description": "HER-id of sender (default = null).",
            "schema": {
              "type": "integer",
              "format": "int32",
              "example": null
            },
            "example": null
          },
          {
            "name": "BusinessDocumentId",
            "in": "query",
            "description": "MsgId in business document (default = null).",
            "schema": {
              "maxLength": 100,
              "minLength": 0,
              "type": "string",
              "example": null
            },
            "example": null
          },
          {
            "name": "IncludeMetadata",
            "in": "query",
            "description": "Whether to include metadata or only include Id and ReceiverHerId of Message in results (default = false).",
            "schema": {
              "type": "boolean",
              "example": false
            },
            "example": false
          },
          {
            "name": "MessagesToFetch",
            "in": "query",
            "description": "How many messages to fetch (default = 10) (If set, must be a number between 1 and 100).",
            "schema": {
              "maximum": 100,
              "minimum": 1,
              "type": "integer",
              "format": "int32",
              "example": 10
            },
            "example": 10
          },
          {
            "name": "OrderBy",
            "in": "query",
            "description": "How to order results (based on GenDate in business document) (default = 1).\n\n- 1 = Ascending\n\n- 2 = Descending",
            "schema": {
              "allOf": [
                {
                  "$ref": "#/components/schemas/OrderBy"
                }
              ],
              "example": "1"
            },
            "example": "1"
          },
          {
            "name": "api-version",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "2"
          },
          {
            "name": "nhn-source-system",
            "in": "header",
            "description": "Name and version for the client system",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "MyApplication, v1.337"
          }
        ],
        "responses": {
          "400": {
            "description": "Bad request - The request body contained invalid data or the request was cancelled",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "Model validation error occurred",
                  "errorCode": 1000,
                  "validationErrors": [
                    "Example error"
                  ],
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "e6098c42-46b5-48c2-8a22-7ea0cd75ebd3"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden - Authenticated client is not authorized to access messages with given HerIds",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "Not authorized for HerId(s): 1234",
                  "errorCode": 0,
                  "validationErrors": null,
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "1131f226-9bab-4604-a373-bb0ce145ba8c"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error - Unexpected server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "An unknown error occurred",
                  "errorCode": 0,
                  "validationErrors": null,
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "9b202395-ceea-4187-ba31-8bd6b6851b71"
                }
              }
            }
          },
          "200": {
            "description": "OK - A list with unread messages matching query parameters",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Message"
                  }
                },
                "example": [
                  {
                    "id": "e8ea3e89-4ee4-4d28-9b4a-246495a97834",
                    "receiverHerId": 42,
                    "senderHerId": 1111,
                    "businessDocumentId": "d1594ad1-2826-462a-a1ed-43b4276387d4",
                    "businessDocumentGenDate": "2025-09-22T05:56:36.3095151+00:00",
                    "isAppRec": false
                  },
                  {
                    "id": "d005d2d3-0eea-4d3a-bb98-ce2456e2a165",
                    "receiverHerId": 1337,
                    "senderHerId": 2222,
                    "businessDocumentId": "3417f8bb-e839-4774-9d31-c96151c1fceb",
                    "businessDocumentGenDate": "2025-09-22T05:56:36.3095192+00:00",
                    "isAppRec": false
                  }
                ]
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "MessagesController"
        ],
        "summary": "Send a message with business document",
        "description": "The request has a max limit of 35 MB",
        "operationId": "PostMessage",
        "parameters": [
          {
            "name": "api-version",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "2"
          },
          {
            "name": "nhn-source-system",
            "in": "header",
            "description": "Name and version for the client system",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "MyApplication, v1.337"
          }
        ],
        "requestBody": {
          "description": "Object with business document and metadata",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/PostMessageRequest"
                  }
                ],
                "description": "Business document (payload) and metadata for POST on Messages"
              }
            },
            "text/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/PostMessageRequest"
                  }
                ],
                "description": "Business document (payload) and metadata for POST on Messages"
              }
            },
            "application/*+json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/PostMessageRequest"
                  }
                ],
                "description": "Business document (payload) and metadata for POST on Messages"
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Bad request - The request contained invalid data or the request was cancelled",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "Model validation error occurred",
                  "errorCode": 1000,
                  "validationErrors": [
                    "Example error"
                  ],
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "a686f859-1a0a-489a-bd77-41f86d273cd2"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden - Authenticated client is not authorized to send message from given HerId",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "Not authorized for HerId(s): 1234",
                  "errorCode": 0,
                  "validationErrors": null,
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "4555ce9a-1ad9-4c49-b893-47088e8ebb68"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error - Unexpected server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "An unknown error occurred",
                  "errorCode": 0,
                  "validationErrors": null,
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "0d5b9658-71e8-44a3-b5ad-6505bce42f58"
                }
              }
            }
          },
          "201": {
            "description": "Created - Response body contains id of created message and Location-header contains url for fetching the created message",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string",
                  "format": "uuid"
                },
                "example": "3d924740-9f7b-4c33-93af-ff72e118d1e6"
              }
            }
          }
        }
      }
    },
    "/Messages/{id}": {
      "get": {
        "tags": [
          "MessagesController"
        ],
        "summary": "Get message with given id",
        "operationId": "GetMessage",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id of message, as received from GET Messages endpoint (must be a valid Guid)",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          },
          {
            "name": "api-version",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "2"
          },
          {
            "name": "nhn-source-system",
            "in": "header",
            "description": "Name and version for the client system",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "MyApplication, v1.337"
          }
        ],
        "responses": {
          "400": {
            "description": "Bad request - The request was cancelled",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "Request was cancelled",
                  "errorCode": 0,
                  "validationErrors": null,
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "80f89b77-68eb-4e9e-ba43-585a960329e4"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden - Authenticated client is not authorized to access messages with given id",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "Not authorized for HerId(s): 1234",
                  "errorCode": 0,
                  "validationErrors": null,
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "7e86953a-c41c-4427-bf69-ca97b862835c"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error - Unexpected server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "An unknown error occurred",
                  "errorCode": 0,
                  "validationErrors": null,
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "875999bc-d1b7-47f8-9192-541dc98d0fd1"
                }
              }
            }
          },
          "200": {
            "description": "OK - Message with given id",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "example": {
                  "id": "e3191b0e-6abb-4433-b5a1-b5af2beafe69",
                  "receiverHerId": 42,
                  "senderHerId": 1111,
                  "businessDocumentId": "81b01cb1-c79c-4962-a8d2-41a8320e1a1a",
                  "businessDocumentGenDate": "2025-09-22T05:56:36.3132829+00:00",
                  "isAppRec": false
                }
              }
            }
          },
          "404": {
            "description": "Not found - Message with given id could not be found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "Could not find database document",
                  "errorCode": 0,
                  "validationErrors": null,
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "fe896e1b-91fe-455f-9173-edf66c7d4c72"
                }
              }
            }
          }
        }
      }
    },
    "/Messages/{id}/business-document": {
      "get": {
        "tags": [
          "MessagesController"
        ],
        "summary": "Get business document for message",
        "operationId": "GetBusinessDocument",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id of message, as received from GET Messages endpoint (must be a valid Guid)",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          },
          {
            "name": "api-version",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "2"
          },
          {
            "name": "nhn-source-system",
            "in": "header",
            "description": "Name and version for the client system",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "MyApplication, v1.337"
          }
        ],
        "responses": {
          "400": {
            "description": "Bad request - The request was cancelled",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "Request was cancelled",
                  "errorCode": 0,
                  "validationErrors": null,
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "3daef4e0-4d05-457c-8d89-c488f13b331f"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden - Authenticated client is not authorized to access message with given id",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "Not authorized for HerId(s): 1234",
                  "errorCode": 0,
                  "validationErrors": null,
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "0ce77bb9-5f09-4b69-b7c9-d66eaacd6869"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error - Unexpected server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "An unknown error occurred",
                  "errorCode": 0,
                  "validationErrors": null,
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "862bfb8a-6ca4-42c9-bff8-7391ad7ca432"
                }
              }
            }
          },
          "200": {
            "description": "OK - Business document for message with given id",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetBusinessDocumentResponse"
                },
                "example": {
                  "businessDocument": "\"PD94bWw+[...]\"",
                  "contentType": "application/xml",
                  "contentTransferEncoding": "base64"
                }
              }
            }
          },
          "404": {
            "description": "Not found - Message with given id could not be found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "Could not find database document",
                  "errorCode": 0,
                  "validationErrors": null,
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "65e82168-20b8-47a9-bd42-34e40e4b8f71"
                }
              }
            }
          }
        }
      }
    },
    "/Messages/{id}/status": {
      "get": {
        "tags": [
          "MessagesController"
        ],
        "summary": "Get message status\nTODO Indicate correct use of this endpoint (e.g. \"Get message status of a sent message\")",
        "description": "When id refers to an application receipt, only StatusInfo.Acknowledged is relevant",
        "operationId": "GetStatus",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id of message, as received from GET Messages endpoint (must be a valid Guid)",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          },
          {
            "name": "api-version",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "2"
          },
          {
            "name": "nhn-source-system",
            "in": "header",
            "description": "Name and version for the client system",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "MyApplication, v1.337"
          }
        ],
        "responses": {
          "400": {
            "description": "Bad request - The request was cancelled",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "Request was cancelled",
                  "errorCode": 0,
                  "validationErrors": null,
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "e22723f3-c9e6-48e8-88fa-a67431a3c901"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden - Authenticated client is not authorized to access message with given id",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "Not authorized for HerId(s): 1234",
                  "errorCode": 0,
                  "validationErrors": null,
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "fb7116c7-3b62-485d-a7d8-ca713ba44d0a"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error - Unexpected server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "An unknown error occurred",
                  "errorCode": 0,
                  "validationErrors": null,
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "cf7698e5-fe1e-466d-8599-8be3973cdf55"
                }
              }
            }
          },
          "200": {
            "description": "OK - A list with statuses for message with given id",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/StatusInfo"
                  }
                },
                "example": [
                  {
                    "receiverHerId": 42,
                    "transportDeliveryState": "Acknowledged",
                    "appRecStatus": "Ok"
                  }
                ]
              }
            }
          },
          "404": {
            "description": "Not found - Message with given id could not be found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "Could not find database document",
                  "errorCode": 0,
                  "validationErrors": null,
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "37ff5212-4153-4eea-8194-d91e7293dea6"
                }
              }
            }
          }
        }
      }
    },
    "/Messages/{id}/apprec/{appRecSenderHerId}": {
      "post": {
        "tags": [
          "MessagesController"
        ],
        "summary": "Send an application receipt for a message",
        "description": "AppRecStatus must be 1 ('OK'), 2 ('Avvist') or 3 ('Ok, feil i delmelding')\n\nAppRecErrorList must be populated if AppRecResult is 'Avvist'\n\nAppRecErrorList.Details is optional\n",
        "operationId": "PostAppRec",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id of the message for which to send application receipt, as received from GET Messages endpoint (must be a valid Guid)",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          },
          {
            "name": "appRecSenderHerId",
            "in": "path",
            "description": "The HER-id of the sender of the application receipt",
            "required": true,
            "schema": {
              "maximum": 2147483647,
              "minimum": 1,
              "type": "integer",
              "format": "int32"
            }
          },
          {
            "name": "api-version",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "2"
          },
          {
            "name": "nhn-source-system",
            "in": "header",
            "description": "Name and version for the client system",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "MyApplication, v1.337"
          }
        ],
        "requestBody": {
          "description": "Application receipt result, potential errors and metadata",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/PostAppRecRequest"
                  }
                ],
                "description": "Information about the application receipt"
              }
            },
            "text/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/PostAppRecRequest"
                  }
                ],
                "description": "Information about the application receipt"
              }
            },
            "application/*+json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/PostAppRecRequest"
                  }
                ],
                "description": "Information about the application receipt"
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Bad request - The request body contained invalid data or the request was cancelled",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "Model validation error occurred",
                  "errorCode": 1000,
                  "validationErrors": [
                    "Example error"
                  ],
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "e0f6c4cf-f181-44bc-b295-832d11e6335b"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden - Authenticated client is not authorized to send application receipts for message with given Id",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "Not authorized for HerId(s): 1234",
                  "errorCode": 0,
                  "validationErrors": null,
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "1d1685cc-0b0c-4301-96fb-7280a8a05b58"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error - Unexpected server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "An unknown error occurred",
                  "errorCode": 0,
                  "validationErrors": null,
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "c5530c03-c7f5-4899-b0ee-a2034cf55009"
                }
              }
            }
          },
          "201": {
            "description": "Created - Response body contains id of created message and Location-header contains url for fetching the created message",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string",
                  "format": "uuid"
                },
                "example": "5fb9867a-3ce7-431a-8ea5-b7e5aa620d30"
              }
            }
          },
          "404": {
            "description": "Not found - Message with given id could not be found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "Could not find database document",
                  "errorCode": 0,
                  "validationErrors": null,
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "a7b76b43-9087-4c2b-a321-1ab6f67bb34c"
                }
              }
            }
          }
        }
      }
    },
    "/Messages/{id}/read/{herId}": {
      "put": {
        "tags": [
          "MessagesController"
        ],
        "summary": "Mark message as read",
        "operationId": "MarkMessageAsRead",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id of message, as received from GET Messages endpoint (must be a valid Guid)",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          },
          {
            "name": "herId",
            "in": "path",
            "description": "HER-id of the receiver/copy receiver of the message",
            "required": true,
            "schema": {
              "maximum": 2147483647,
              "minimum": 1,
              "type": "integer",
              "format": "int32"
            }
          },
          {
            "name": "api-version",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "2"
          },
          {
            "name": "nhn-source-system",
            "in": "header",
            "description": "Name and version for the client system",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "MyApplication, v1.337"
          }
        ],
        "responses": {
          "400": {
            "description": "Bad request - The request contained invalid data or the request was cancelled",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "Model validation error occurred",
                  "errorCode": 1000,
                  "validationErrors": [
                    "Example error"
                  ],
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "71829606-7ad6-4d50-91d3-778c067374f8"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden - Authenticated client is not authorized to access message with given id",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "Not authorized for HerId(s): 1234",
                  "errorCode": 0,
                  "validationErrors": null,
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "20a098e0-5551-43b4-a317-c51abaf73023"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error - Unexpected server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "An unknown error occurred",
                  "errorCode": 0,
                  "validationErrors": null,
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "a83e57cc-d449-467c-a22b-95694dd88a00"
                }
              }
            }
          },
          "204": {
            "description": "No content - Message with given id has been marked as read"
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "error": "Request was cancelled",
                  "errorCode": 0,
                  "validationErrors": null,
                  "stackTrace": "[StackTrace] (not set in Prod)",
                  "requestId": "2ec33026-f03e-4ff3-bd04-e2ef4b317adc"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "AppRecError": {
        "required": [
          "details",
          "errorCode"
        ],
        "type": "object",
        "properties": {
          "errorCode": {
            "type": "string",
            "description": "Application receipt error code.",
            "nullable": true,
            "example": "E10"
          },
          "details": {
            "type": "string",
            "description": "Details about the error.",
            "nullable": true,
            "example": ""
          },
          "description": {
            "type": "string",
            "nullable": true
          },
          "oid": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false,
        "description": "Information about an error in the application receipt."
      },
      "AppRecStatus": {
        "enum": [
          "Ok",
          "Rejected",
          "OkErrorInMessagePart"
        ],
        "type": "string",
        "description": "Application receipt status\n\n- Ok = \"Ok\"\n\n- Rejected = \"Avvist\"\n\n- OkErrorInMessagePart = \"Ok, feil i delmelding\" NB! Not supported as of this writing.\n"
      },
      "ApprecInfo": {
        "required": [
          "receiverHerId"
        ],
        "type": "object",
        "properties": {
          "receiverHerId": {
            "type": "integer",
            "description": "The HER-id of the receiver/copy receiver of the business document",
            "format": "int32"
          },
          "appRecStatus": {
            "allOf": [
              {
                "$ref": "#/components/schemas/AppRecStatus"
              }
            ],
            "description": "Application receipt status. Value 'null' if not received",
            "nullable": true
          },
          "appRecErrorList": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/AppRecError"
            },
            "description": "List with errors in the application receipt, if any",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "DeliveryState": {
        "enum": [
          "Unconfirmed",
          "Acknowledged",
          "Rejected"
        ],
        "type": "string"
      },
      "EbXmlInfo": {
        "type": "object",
        "properties": {
          "cpaId": {
            "type": "string",
            "description": "If not set, value according to HIS 1037:2011 will be generated.",
            "nullable": true
          },
          "conversationId": {
            "type": "string",
            "description": "If not set, value according to HIS 1037:2011 will be generated.",
            "nullable": true
          },
          "service": {
            "type": "string",
            "description": "If not set, value according to HIS 1209:2018 will be generated.",
            "nullable": true
          },
          "serviceType": {
            "type": "string",
            "description": "If not set, value according to HIS 1209:2018 will be generated.",
            "nullable": true
          },
          "action": {
            "type": "string",
            "description": "If not set, value will be resolved from BusinessDocument.",
            "nullable": true
          },
          "senderRole": {
            "type": "string",
            "description": "If not set, value according to HIS 1209:2018 will be generated.",
            "nullable": true
          },
          "useSenderLevel1HerId": {
            "type": "boolean",
            "description": "If set to 'true', then HerId from the organisation-level (level1) will be used as sender",
            "nullable": true
          },
          "receiverRole": {
            "type": "string",
            "description": "If not set, value according to HIS 1209:2018 will be generated.",
            "nullable": true
          },
          "applicationName": {
            "type": "string",
            "description": "Name of application or EPJ. HIS 1210:2018",
            "nullable": true,
            "example": "\"EPJ Front\""
          },
          "applicationVersion": {
            "type": "string",
            "description": "Version of application or EPJ. HIS 1210:2018",
            "nullable": true,
            "example": "\"18.0.8\""
          },
          "middlewareName": {
            "type": "string",
            "description": "Some systems use a middleware between application and messagehandler. Name can be provided here. HIS 1210:2018",
            "nullable": true
          },
          "middlewareVersion": {
            "type": "string",
            "description": "Some systems use a middleware between application and messagehandler. Version can be provided here. HIS 1210:2018",
            "nullable": true
          },
          "compressPayload": {
            "type": "boolean",
            "description": "Some systems expect the businessdocument to be compressed before encrypted and added to Ebxml.\nWhen set to 'true' the payload will be compressed using the Gzip algorithm",
            "nullable": true
          }
        },
        "additionalProperties": false,
        "description": "Information to be used for the EBXML generation"
      },
      "ErrorMessage": {
        "required": [
          "requestId"
        ],
        "type": "object",
        "properties": {
          "error": {
            "type": "string",
            "description": "Description of error.",
            "nullable": true
          },
          "errorCode": {
            "type": "integer",
            "description": "Error code associated with error.",
            "format": "int32"
          },
          "validationErrors": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Which validation errors that led to error, if any.",
            "nullable": true
          },
          "stackTrace": {
            "type": "string",
            "description": "Only used in Development-environments, will be null in PROD.",
            "nullable": true
          },
          "requestId": {
            "type": "string",
            "description": "Current Request id for log-tracking."
          }
        },
        "additionalProperties": false,
        "description": "Information about an error that has occured while processing a request."
      },
      "GetBusinessDocumentResponse": {
        "required": [
          "businessDocument",
          "contentTransferEncoding",
          "contentType"
        ],
        "type": "object",
        "properties": {
          "businessDocument": {
            "minLength": 1,
            "type": "string",
            "description": "The business document - Payload.\n\nThe BusinessDocument is the raw bytes of the payload encoded with ContentTransferEncoding",
            "example": "\"PD94bWw+[...]\""
          },
          "contentType": {
            "minLength": 1,
            "type": "string",
            "description": "Content type for the business document.\n\nMost payloads should be xml",
            "example": "\"application/xml\""
          },
          "contentTransferEncoding": {
            "minLength": 1,
            "type": "string",
            "description": "Content transfer encoding for the business document.\n\nPayload is always base64-encoded.",
            "example": "\"base64\""
          }
        },
        "additionalProperties": false,
        "description": "Business document (payload) and metadata returned from GET/business-document on Messages"
      },
      "Message": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "Internal id of message. To be used when using messages/{id}/*-endpoints.\n\nWill always be a valid Guid",
            "format": "uuid",
            "nullable": true,
            "example": "5f5e94d5-d908-476b-a172-a241c52eddb6"
          },
          "contentType": {
            "type": "string",
            "description": "Content type for the business document",
            "nullable": true,
            "example": "\"application/xml\""
          },
          "receiverHerId": {
            "type": "integer",
            "description": "HER-id of receiver.",
            "format": "int32",
            "nullable": true,
            "example": 1337
          },
          "senderHerId": {
            "type": "integer",
            "description": "HER-id of sender (will not be present if includeMetadata = false).",
            "format": "int32",
            "nullable": true,
            "example": 1111
          },
          "businessDocumentId": {
            "type": "string",
            "description": "MsgId in business document (will not be present if includeMetadata = false).",
            "nullable": true,
            "example": "9f1c892b-4341-4239-b627-83b7a1eb65ab"
          },
          "businessDocumentGenDate": {
            "type": "string",
            "description": "GenDate in business document (will not be present if includeMetadata = false).",
            "format": "date-time",
            "nullable": true,
            "example": "2024-09-03T07:55:13"
          },
          "isAppRec": {
            "type": "boolean",
            "description": "Whether business document is an application receipt (will not be present if includeMetadata = false).",
            "nullable": true,
            "example": false
          }
        },
        "additionalProperties": false
      },
      "OrderBy": {
        "enum": [
          "Ascending",
          "Descending"
        ],
        "type": "string",
        "description": "How to order results based on GenDate in business document."
      },
      "PostAppRecRequest": {
        "required": [
          "appRecStatus"
        ],
        "type": "object",
        "properties": {
          "appRecStatus": {
            "allOf": [
              {
                "$ref": "#/components/schemas/AppRecStatus"
              }
            ],
            "description": "The status of the application receipt sent for a received message\n\n1 = Ok, 2 = Avvist, 3 = Ok, feil i delmelding",
            "example": "1"
          },
          "appRecErrorList": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/AppRecError"
            },
            "description": "List of errors in application receipt",
            "nullable": true
          },
          "ebXmlOverrides": {
            "allOf": [
              {
                "$ref": "#/components/schemas/EbXmlInfo"
              }
            ],
            "description": "One or more EbXml-properties can be provided if business process has special requirements.\n\nFor most business processes the values can and will be resolved from the business document\nby the server, and therefore does not have to be applied twice.\nCurrent implementation is following 'HIS 1037:2011' and 'HIS 1209:2018'\n",
            "nullable": true
          }
        },
        "additionalProperties": false,
        "description": "Information about the application receipt"
      },
      "PostMessageRequest": {
        "required": [
          "businessDocument",
          "contentTransferEncoding",
          "contentType"
        ],
        "type": "object",
        "properties": {
          "businessDocument": {
            "minLength": 1,
            "type": "string",
            "description": "The business document - Payload.\n\nIt is required that the encoding in the XML-document is UTF-8, and that this is declared in the first line.\nExample: `<xml version=\"1.0\" encoding=\"UTF-8\" />`.\n\nThe payload must be of type and encoding as specified in ContentType and ContentTransferEncoding, meaning that the\npayload should always be an XML-document as a base64-encoded string.",
            "example": "\"PD94bWw+[...]\""
          },
          "contentType": {
            "minLength": 1,
            "type": "string",
            "description": "Content type for the business document.\n\nNB! Payload should always be an XML-document as a base64-encoded string.",
            "example": "\"application/xml\""
          },
          "contentTransferEncoding": {
            "minLength": 1,
            "type": "string",
            "description": "Content transfer encoding for the business document.\n\nNB! Payload should always be base64-encoded.",
            "example": "\"base64\""
          },
          "ebXmlOverrides": {
            "allOf": [
              {
                "$ref": "#/components/schemas/EbXmlInfo"
              }
            ],
            "description": "One or more EbXml-properties can be provided if business process has special requirements.\n\nFor most business processes the values can and will be resolved from the business document\nby the server, and therefore does not have to be applied twice.\nCurrent implementation is following 'HIS 1037:2011' and 'HIS 1209:2018'\n",
            "nullable": true
          },
          "receiverHerIdsSubset": {
            "type": "array",
            "items": {
              "type": "integer",
              "format": "int32"
            },
            "description": "The Business document might contain many receivers, but only the receivers listed here\nshould be handled by Meldingstjener",
            "nullable": true
          }
        },
        "additionalProperties": false,
        "description": "Business document (payload) and metadata for POST on Messages"
      },
      "StatusInfo": {
        "required": [
          "receiverHerId",
          "transportDeliveryState"
        ],
        "type": "object",
        "properties": {
          "receiverHerId": {
            "type": "integer",
            "description": "The HER-id of the receiver/copy receiver of the business document",
            "format": "int32"
          },
          "transportDeliveryState": {
            "allOf": [
              {
                "$ref": "#/components/schemas/DeliveryState"
              }
            ],
            "description": "Transport delivery state for the message"
          },
          "appRecStatus": {
            "allOf": [
              {
                "$ref": "#/components/schemas/AppRecStatus"
              }
            ],
            "description": "Application receipt status. Value 'null' if not received.",
            "nullable": true
          }
        },
        "additionalProperties": false,
        "description": "Status information about the message exchange"
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "description": "Put **_ONLY_** your JWT Bearer token in text box below!",
        "scheme": "Bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "security": [
    {
      "Bearer": []
    }
  ],
  "servers": [
    {
      "url": "https://api.hn-tjener.prod.melding.nhn.no"
    }
  ]
}